[package]
name = "forge-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Developer CLI for The Forge Protocol"

[dependencies]
clap = { version = "4", features = ["derive"] }
ring = { workspace = true }
serde_json = { workspace = true }
forge-crypto = { path = "../../crates/forge-crypto" }
forge-merkle = { path = "../../crates/forge-merkle" }
beskar-export = { path = "../../crates/beskar-export" }
